export const SET_LOGIN_MODE = "SET_LOGIN_MODE";
export const SET_REIGSTER_MODE = "SET_REGISTER_MODE";
export const LOGIN_START = "LOGIN_START";
export const LOGIN_END = "LOGIN_END";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const REGISTER_START = "REGISTER_START";
export const REGISTER_END = "REGISTER_END";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const AUTO_LOGIN = "AUTO_LOGIN";
export const AUTO_LOGOUT = "AUTO_LOGOUT";

export const GET_OPINIONS = "GET_OPINIONS";
export const ADD_OPINION = "ADD_OPINION";
export const SEND_OPINIONS = "SEND_OPINIONS";

export const GET_PATIENTS_NAMES = "GET_PATIENTS_NAMES";
export const GET_PATIENT_RESULTS = "GET_PATIENT_RESULTS";
export const GET_PATIENT_RESULTS_SCANS = "GET_PATIENTS_RESULT_SCANS";
export const SET_PATIENTS_NAMES = "SET_PATIENTS_NAMES";
export const REMOVE_PATIENT_NAME = "REMOVE_PATIENT_NAME";
